### ISSUE TITLE
roc-package-webpack-dev on roc-package-web-app-react-dev is missing

### ISSUE THREAD

**Issue by RaonyMarcondes** [rocjs/roc-template-web-app-react#7]
![captura de tela 2016-04-19 as 11 36 45](https://cloud.githubusercontent.com/assets/1424842/14643130/90a7098a-0623-11e6-80de-dce1cb7f0237.png)

**Comment by dlmr** [comment]
This might be related to npm. What version are you using? `npm --version`

**Comment by RaonyMarcondes** [comment]
Indeed... i was running 3.8.2, update npm to 3.8.6 and node to 5.10.1 and works just fine :)

**Comment by dlmr** [comment]
I'm assuming that you mean **2.8.2** here. 🙂 

Awesome that you made it work and thanks for reporting it! We will look more into supporting npm@2 out of the box in the future.
